# Generated by Django 3.1.4 on 2020-12-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='location',
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='location',
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='location',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
