# Generated by Django 3.1.4 on 2020-12-08 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageEnquiry',
            new_name='UserMessage',
        ),
    ]
