# Generated by Django 3.1.2 on 2020-12-06 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0002_auto_20201206_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='image_url',
            new_name='img1',
        ),
    ]
