# Generated by Django 3.1.4 on 2020-12-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0002_auto_20201220_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_logged_in',
            field=models.BooleanField(default=False, verbose_name='isLoggedIn'),
        ),
    ]
