# Generated by Django 3.1.4 on 2020-12-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0002_auto_20201220_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='product_manufacturers',
            field=models.TextField(default='---', null=True),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='product_name',
            field=models.TextField(default='---', null=True),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='product_year',
            field=models.TextField(default='---', null=True),
        ),
    ]
