# Generated by Django 3.1.5 on 2021-01-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0003_auto_20201225_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_logged_in',
            field=models.BooleanField(default=False, verbose_name='isLoggedIn'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='reply',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='static/img/user_dp'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='query',
            field=models.TextField(default=' ', null=True),
        ),
    ]
