# Generated by Django 3.1.2 on 2020-12-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0003_auto_20201206_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img1',
            field=models.CharField(default='', max_length=2083),
        ),
    ]
