# Generated by Django 3.1.2 on 2020-12-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0004_auto_20201206_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='img2',
            field=models.CharField(default='', max_length=2083),
        ),
        migrations.AddField(
            model_name='products',
            name='img3',
            field=models.CharField(default='', max_length=2083),
        ),
        migrations.AddField(
            model_name='products',
            name='img4',
            field=models.CharField(default='', max_length=2083),
        ),
        migrations.AddField(
            model_name='products',
            name='img5',
            field=models.CharField(default='', max_length=2083),
        ),
    ]
