# Generated by Django 3.1.2 on 2020-12-06 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0005_auto_20201206_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='year',
        ),
        migrations.AddField(
            model_name='products',
            name='year',
            field=models.CharField(default='####', max_length=4, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
