# Generated by Django 3.1.2 on 2020-12-06 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0008_auto_20201206_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesories',
            name='model',
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_info',
            field=models.CharField(default='############', max_length=12, validators=[django.core.validators.MinLengthValidator(12)]),
        ),
    ]
