# Generated by Django 3.1.2 on 2020-12-06 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0008_auto_20201206_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesories',
            name='model',
        ),
    ]
