# Generated by Django 3.1.3 on 2020-12-06 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0009_auto_20201206_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesories',
            name='model',
        ),
    ]
