# Generated by Django 3.1.2 on 2020-12-07 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0009_auto_20201206_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_info',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.MinLengthValidator(12)]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='img1',
            field=models.CharField(blank=True, default='', max_length=2083),
        ),
        migrations.AlterField(
            model_name='products',
            name='img2',
            field=models.CharField(blank=True, default='', max_length=2083),
        ),
        migrations.AlterField(
            model_name='products',
            name='img3',
            field=models.CharField(blank=True, default='', max_length=2083),
        ),
        migrations.AlterField(
            model_name='products',
            name='img4',
            field=models.CharField(blank=True, default='', max_length=2083),
        ),
        migrations.AlterField(
            model_name='products',
            name='img5',
            field=models.CharField(blank=True, default='', max_length=2083),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='products',
            name='year',
            field=models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
